// ================================================================
// CEO DASHBOARD (pages/dashboards/CEODashboard.tsx)
// ================================================================
// PURPOSE: Executive dashboard for the CEO role (view-only).
//
// SECTIONS:
//   - Executive summary cards (projects, revenue, team)
//   - Financial metrics charts
//   - Project status overview (active, completed, at-risk)
//   - Team performance metrics
//   - Recent activity feed
//
// DATA: Calls analyticsService for aggregated data
// ROLE ACCESS: CEO only (view-only, no editing)
// ================================================================

import React, { useState, useEffect } from 'react';
import {
  Box,
  Grid,
  Card,
  CardContent,
  Typography,
  Alert,
  Tabs,
  Tab,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  LinearProgress,
  Divider,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  Button,
  CircularProgress
} from '@mui/material';
import {
  TrendingUp as TrendingUpIcon,
  AttachMoney as RevenueIcon,
  Business as ProjectsIcon,
  People as TeamIcon,
  Assessment as AnalyticsIcon,
  Warning as RiskIcon,
  CheckCircle as SuccessIcon,
  Timeline as GrowthIcon,
  AccountBalance as FinanceIcon,
  Dashboard as DashboardIcon,
  Assessment as AssessmentIcon,
  Download as DownloadIcon,
  Description as ReportIcon
} from '@mui/icons-material';

import DashboardLayout from '../../components/DashboardLayout';    // Page wrapper with sidebar
import { useNavigate } from 'react-router-dom';                      // Navigation
import api from '../../services/api';                                // Axios instance
import analyticsService from '../../services/analyticsService';     // CEO-specific analytics
import toast from 'react-hot-toast';

// ─── TYPE: High-level business numbers for the CEO ───
interface ExecutiveSummary {
  totalRevenue: number;
  revenueGrowth: number;        // % growth
  activeProjects: number;
  completedProjects: number;
  totalEmployees: number;
  clientSatisfaction: number;   // % score
  profitMargin: number;         // %
  marketShare: number;          // %
}

// ─── TYPE: One project row in the CEO's project table ───
interface ProjectSummary {
  id: string;
  name: string;
  value: number;                             // Project value in currency
  status: 'on_track' | 'at_risk' | 'delayed'; // Traffic-light status
  completion: number;                        // 0-100%
  client: string;
  manager: string;
}

// ─── TYPE: One row in the financial metrics table ───
interface FinancialMetric {
  quarter: string;    // e.g. "Q1 2024"
  revenue: number;
  profit: number;
  margin: number;     // profit/revenue %
}

// ─── TYPE: A report generated by admin for CEO viewing ───
interface CEOReport {
  id: string;
  title: string;
  description: string;
  sheetId: string;
  projectId: string;
  createdAt: string;
  metadata: any;
}

// ─── CEO DASHBOARD COMPONENT (View-Only) ───
// The CEO cannot edit anything — this is a read-only executive overview.
const CEODashboard: React.FC = () => {
  const navigate = useNavigate();
  const [tabValue, setTabValue] = useState(0);  // Active tab
  // Initialize with sample/placeholder data (replaced by API data when loaded)
  const [summary, setSummary] = useState<ExecutiveSummary>({
    totalRevenue: 28500000,
    revenueGrowth: 15.8,
    activeProjects: 12,
    completedProjects: 35,
    totalEmployees: 145,
    clientSatisfaction: 94.2,
    profitMargin: 18.5,
    marketShare: 12.3
  });
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [financials, setFinancials] = useState<FinancialMetric[]>([]);
  const [loading, setLoading] = useState(true);
  const [reports, setReports] = useState<CEOReport[]>([]);           // CEO reports from admin
  const [reportsLoading, setReportsLoading] = useState(false);
  const [downloadingId, setDownloadingId] = useState<string | null>(null); // Which report is being downloaded

  useEffect(() => {
    loadDashboardData();
    
    // Set up real-time data refresh every 30 seconds
    const interval = setInterval(() => {
      loadDashboardData();
    }, 30000);
    
    // Also listen for window focus to refresh data
    const handleFocus = () => loadDashboardData();
    window.addEventListener('focus', handleFocus);
    
    return () => {
      clearInterval(interval);
      window.removeEventListener('focus', handleFocus);
    };
  }, []);

  const loadDashboardData = async () => {
    try {
      setLoading(true);
      
      // Load real data from APIs
      const [usersResponse, projectsResponse, analyticsData] = await Promise.all([
        api.get('/auth/users').catch(() => ({ data: { users: [] } })),
        api.get('/projects').catch(() => ({ data: [] })),
        analyticsService.getExecutiveSummary()
      ]);
      
      const users = usersResponse.data.users || [];
      const projectsData = projectsResponse.data || [];
      
      // Calculate real summary metrics
      const activeProjects = projectsData.filter((p: any) => p.status === 'IN_PROGRESS').length;
      const completedProjects = projectsData.filter((p: any) => p.status === 'COMPLETED').length;
      const totalRevenue = projectsData.reduce((sum: number, p: any) => sum + (p.budget || 0), 0);
      
      setSummary({
        totalRevenue,
        revenueGrowth: analyticsData.revenueGrowth,
        activeProjects,
        completedProjects,
        totalEmployees: users.length,
        clientSatisfaction: analyticsData.clientSatisfaction,
        profitMargin: analyticsData.profitMargin,
        marketShare: analyticsData.marketShare
      });
      
      // Transform projects data for display
      const transformedProjects = projectsData.slice(0, 10).map((project: any) => ({
        id: project.id,
        name: project.name,
        value: project.budget || 0,
        status: project.status === 'IN_PROGRESS' ? 'on_track' : 
                project.status === 'ON_HOLD' ? 'at_risk' : 
                project.status === 'COMPLETED' ? 'on_track' : 'delayed',
        completion: project.progressPercentage || 0,
        client: project.client || 'N/A',
        manager: project.creator ? `${project.creator.firstName} ${project.creator.lastName}` : 'N/A'
      }));
      
      setProjects(transformedProjects);
      
      // Load financial trends
      const trends = await analyticsService.getFinancialTrends(4);
      setFinancials(trends.length > 0 ? trends : [
        { quarter: 'Q4 2025', revenue: totalRevenue * 0.2, profit: totalRevenue * 0.037, margin: 18.5 },
        { quarter: 'Q1 2026', revenue: totalRevenue * 0.25, profit: totalRevenue * 0.0475, margin: 19.0 },
        { quarter: 'Q2 2026 (Projected)', revenue: totalRevenue * 0.3, profit: totalRevenue * 0.057, margin: 19.0 },
        { quarter: 'Q3 2026 (Projected)', revenue: totalRevenue * 0.25, profit: totalRevenue * 0.0475, margin: 19.0 }
      ]);
      
    } catch (error) {
      console.error('Failed to load dashboard data:', error);
      toast.error('Failed to load dashboard data');
    } finally {
      setLoading(false);
    }
  };

  // ── Load CEO Reports ──
  // Fetches all reports that admins have generated for the CEO
  const loadReports = async () => {
    try {
      setReportsLoading(true);
      const response = await api.get('/ceo-reports');
      if (response.data.success) {
        setReports(response.data.data || []);
      }
    } catch (error) {
      console.error('Failed to load reports:', error);
    } finally {
      setReportsLoading(false);
    }
  };

  // ── Download Report as Excel ──
  // Requests the Excel file from the backend and triggers a browser download
  const handleDownloadReport = async (reportId: string, reportTitle: string) => {
    try {
      setDownloadingId(reportId);
      const response = await api.get(`/ceo-reports/${reportId}/download`, {
        responseType: 'blob'   // Binary file data, not JSON
      });

      // Create a temporary URL pointing to the file blob
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      // Clean the title for a safe filename
      const safeTitle = reportTitle.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_');
      link.setAttribute('download', `CEO_Report_${safeTitle}_${Date.now()}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
      window.URL.revokeObjectURL(url);
      toast.success('📥 Report downloaded successfully!');
    } catch (error: any) {
      console.error('Failed to download report:', error);
      toast.error('Failed to download report');
    } finally {
      setDownloadingId(null);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'on_track': return 'success';
      case 'at_risk': return 'warning';
      case 'delayed': return 'error';
      default: return 'default';
    }
  };

  const ExecutiveStatCard = ({ title, value, subtitle, icon, color = 'primary', trend }: any) => (
    <Card>
      <CardContent>
        <Box display="flex" alignItems="center" justifyContent="space-between">
          <Box>
            <Typography variant="h4" color={color}>
              {value}
            </Typography>
            <Typography variant="h6" color="text.secondary">
              {title}
            </Typography>
            {subtitle && (
              <Typography variant="body2" color={trend > 0 ? 'success.main' : 'error.main'}>
                {trend > 0 ? '↗' : '↘'} {subtitle}
              </Typography>
            )}
          </Box>
          <Box sx={{ color: `${color}.main` }}>
            {icon}
          </Box>
        </Box>
      </CardContent>
    </Card>
  );

  const renderExecutiveSummary = () => (
    <Box>
      <Grid container spacing={3} sx={{ mb: 4 }}>
        <Grid item xs={12} sm={6} md={3}>
          <ExecutiveStatCard
            title="Total Revenue"
            value={`$${(summary.totalRevenue / 1000000).toFixed(1)}M`}
            subtitle={`${summary.revenueGrowth}% growth`}
            trend={summary.revenueGrowth}
            icon={<RevenueIcon fontSize="large" />}
            color="success"
          />
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <ExecutiveStatCard
            title="Active Projects"
            value={summary.activeProjects}
            subtitle={`${summary.completedProjects} completed`}
            trend={1}
            icon={<ProjectsIcon fontSize="large" />}
            color="primary"
          />
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <ExecutiveStatCard
            title="Team Size"
            value={summary.totalEmployees}
            subtitle="Across all projects"
            trend={1}
            icon={<TeamIcon fontSize="large" />}
            color="info"
          />
        </Grid>
        <Grid item xs={12} sm={6} md={3}>
          <ExecutiveStatCard
            title="Profit Margin"
            value={`${summary.profitMargin}%`}
            subtitle="Above industry avg"
            trend={1}
            icon={<AnalyticsIcon fontSize="large" />}
            color="warning"
          />
        </Grid>
      </Grid>

      <Alert severity="info" sx={{ mb: 3 }}>
        <Typography variant="h6">Executive Dashboard</Typography>
        <Typography variant="body2">
          Strategic overview of company performance, project portfolio, and key business metrics.
        </Typography>
      </Alert>

      <Grid container spacing={3}>
        <Grid item xs={12} lg={8}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                <ProjectsIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
                Key Project Performance
              </Typography>
              {projects.slice(0, 4).map((project) => (
                <Box key={project.id} sx={{ mb: 3 }}>
                  <Box display="flex" justifyContent="space-between" alignItems="center" mb={1}>
                    <Typography variant="subtitle1">{project.name}</Typography>
                    <Chip
                      label={project.status.replace('_', ' ').toUpperCase()}
                      color={getStatusColor(project.status) as any}
                      size="small"
                    />
                  </Box>
                  <LinearProgress 
                    variant="determinate" 
                    value={project.completion} 
                    sx={{ mb: 1 }}
                    color={getStatusColor(project.status) as any}
                  />
                  <Grid container spacing={2}>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="body2" color="text.secondary">
                        Value: ${(project.value / 1000000).toFixed(1)}M
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="body2" color="text.secondary">
                        Progress: {project.completion}%
                      </Typography>
                    </Grid>
                    <Grid item xs={12} sm={4}>
                      <Typography variant="body2" color="text.secondary">
                        Client: {project.client}
                      </Typography>
                    </Grid>
                  </Grid>
                </Box>
              ))}
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} lg={4}>
          <Card sx={{ mb: 3 }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                <AnalyticsIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
                Key Metrics
              </Typography>
              <List>
                <ListItem>
                  <ListItemIcon>
                    <SuccessIcon color="success" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Client Satisfaction"
                    secondary={`${summary.clientSatisfaction}%`}
                  />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <GrowthIcon color="primary" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Market Share"
                    secondary={`${summary.marketShare}%`}
                  />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <TrendingUpIcon color="success" />
                  </ListItemIcon>
                  <ListItemText
                    primary="Revenue Growth"
                    secondary={`${summary.revenueGrowth}% YoY`}
                  />
                </ListItem>
                <ListItem>
                  <ListItemIcon>
                    <RiskIcon color="warning" />
                  </ListItemIcon>
                  <ListItemText
                    primary="At-Risk Projects"
                    secondary={`${projects.filter(p => p.status === 'at_risk' || p.status === 'delayed').length} of ${projects.length}`}
                  />
                </ListItem>
              </List>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );

  const renderProjectPortfolio = () => (
    <Box>
      <Typography variant="h5" gutterBottom>Project Portfolio</Typography>
      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>Project Name</TableCell>
              <TableCell>Client</TableCell>
              <TableCell>Value</TableCell>
              <TableCell>Status</TableCell>
              <TableCell>Completion</TableCell>
              <TableCell>Project Manager</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {projects.map((project) => (
              <TableRow key={project.id} hover sx={{ cursor: 'pointer' }} onClick={() => navigate(`/project/${project.id}`)}>
                <TableCell>
                  <Typography variant="subtitle2" color="primary">{project.name}</Typography>
                </TableCell>
                <TableCell>{project.client}</TableCell>
                <TableCell>${(project.value / 1000000).toFixed(1)}M</TableCell>
                <TableCell>
                  <Chip
                    label={project.status.replace('_', ' ').toUpperCase()}
                    color={getStatusColor(project.status) as any}
                    size="small"
                  />
                </TableCell>
                <TableCell>
                  <Box display="flex" alignItems="center" gap={1}>
                    <LinearProgress 
                      variant="determinate" 
                      value={project.completion} 
                      sx={{ flexGrow: 1, height: 8 }}
                      color={getStatusColor(project.status) as any}
                    />
                    <Typography variant="body2">{project.completion}%</Typography>
                  </Box>
                </TableCell>
                <TableCell>{project.manager}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );

  const renderFinancialOverview = () => (
    <Box>
      <Typography variant="h5" gutterBottom>Financial Performance</Typography>
      <Grid container spacing={3}>
        <Grid item xs={12} lg={8}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                <FinanceIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
                Quarterly Performance
              </Typography>
              <TableContainer>
                <Table>
                  <TableHead>
                    <TableRow>
                      <TableCell>Quarter</TableCell>
                      <TableCell>Revenue</TableCell>
                      <TableCell>Profit</TableCell>
                      <TableCell>Margin</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {financials.map((metric) => (
                      <TableRow key={metric.quarter}>
                        <TableCell>{metric.quarter}</TableCell>
                        <TableCell>${(metric.revenue / 1000000).toFixed(1)}M</TableCell>
                        <TableCell>${(metric.profit / 1000000).toFixed(1)}M</TableCell>
                        <TableCell>{metric.margin}%</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} lg={4}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>Financial Highlights</Typography>
              <List>
                <ListItem>
                  <ListItemText
                    primary="Total Contract Value"
                    secondary={`$${(projects.reduce((sum, p) => sum + p.value, 0) / 1000000).toFixed(1)}M`}
                  />
                </ListItem>
                <Divider />
                <ListItem>
                  <ListItemText
                    primary="Average Project Value"
                    secondary={`$${(projects.reduce((sum, p) => sum + p.value, 0) / projects.length / 1000000).toFixed(1)}M`}
                  />
                </ListItem>
                <Divider />
                <ListItem>
                  <ListItemText
                    primary="Revenue Per Employee"
                    secondary={`$${Math.round(summary.totalRevenue / summary.totalEmployees / 1000)}K`}
                  />
                </ListItem>
                <Divider />
                <ListItem>
                  <ListItemText
                    primary="Client Retention Rate"
                    secondary="96.5%"
                  />
                </ListItem>
              </List>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );

  // ── Reports Tab ──
  // Shows all reports generated by admins, with Excel download buttons
  const renderReports = () => {
    // Load reports when this tab is first shown
    if (reports.length === 0 && !reportsLoading) {
      loadReports();
    }

    return (
      <Box>
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
          <Typography variant="h5">
            <ReportIcon sx={{ mr: 1, verticalAlign: 'middle' }} />
            Reports from Admin
          </Typography>
          <Button variant="outlined" onClick={loadReports} disabled={reportsLoading}>
            {reportsLoading ? <CircularProgress size={20} /> : 'Refresh'}
          </Button>
        </Box>

        {reportsLoading ? (
          <Box display="flex" justifyContent="center" py={4}>
            <CircularProgress />
          </Box>
        ) : reports.length === 0 ? (
          <Paper sx={{ p: 4, textAlign: 'center' }}>
            <ReportIcon sx={{ fontSize: 60, color: 'text.secondary', mb: 2 }} />
            <Typography variant="h6" color="text.secondary">
              No reports available yet
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Reports will appear here once the admin generates them from project sheets.
            </Typography>
          </Paper>
        ) : (
          <Grid container spacing={3}>
            {reports.map((report) => (
              <Grid item xs={12} md={6} key={report.id}>
                <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Typography variant="h6" gutterBottom>
                      {report.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                      {report.description || 'No description provided'}
                    </Typography>
                    <Divider sx={{ my: 1 }} />
                    <Typography variant="caption" color="text.secondary" display="block">
                      Generated: {new Date(report.createdAt).toLocaleString()}
                    </Typography>
                    {report.metadata?.generatedBy && (
                      <Typography variant="caption" color="text.secondary" display="block">
                        By: {report.metadata.generatedBy}
                      </Typography>
                    )}
                  </CardContent>
                  <Box sx={{ p: 2, pt: 0 }}>
                    <Button
                      variant="contained"
                      color="success"
                      fullWidth
                      startIcon={downloadingId === report.id ? <CircularProgress size={20} color="inherit" /> : <DownloadIcon />}
                      onClick={() => handleDownloadReport(report.id, report.title)}
                      disabled={downloadingId === report.id}
                    >
                      {downloadingId === report.id ? 'Downloading...' : 'Download Excel Report'}
                    </Button>
                  </Box>
                </Card>
              </Grid>
            ))}
          </Grid>
        )}
      </Box>
    );
  };

  return (
    <DashboardLayout 
      title="Chief Executive Officer"
      menuItems={[
        { label: 'Dashboard', path: '/ceo', icon: <DashboardIcon /> },
        { label: 'Reports', path: '/ceo/reports', icon: <AssessmentIcon /> },
      ]}
    >
      <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 3 }}>
        <Tabs value={tabValue} onChange={(_, newValue) => setTabValue(newValue)}>
          <Tab label="Executive Summary" />
          <Tab label="Project Portfolio" />
          <Tab label="Financial Overview" />
          <Tab label="📊 Reports" />
        </Tabs>
      </Box>

      {loading ? (
        <Box display="flex" justifyContent="center" mt={4}>
          <Typography>Loading...</Typography>
        </Box>
      ) : (
        <>
          {tabValue === 0 && renderExecutiveSummary()}
          {tabValue === 1 && renderProjectPortfolio()}
          {tabValue === 2 && renderFinancialOverview()}
          {tabValue === 3 && renderReports()}
        </>
      )}
    </DashboardLayout>
  );
};

export default CEODashboard;