# Generated by Django 6.0.1 on 2026-01-28 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, help_text='Supervisors assigned to execute work on this project.', related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
