# Generated by Django 6.0.1 on 2026-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requirementsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project area size (e.g., 1250.50).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='area_unit',
            field=models.CharField(blank=True, help_text='Unit for area size (e.g., sqft, sqm).', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget for the project.', max_digits=14, null=True),
        ),
    ]
