# Generated by Django 6.0.1 on 2026-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_set_admin_role_for_superusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('pending_acceptance', 'Pending Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending_completion', 'Pending Completion Approval'), ('approved', 'Approved')], default='pending_acceptance', help_text='Tracks the approval workflow state', max_length=32),
        ),
    ]
