# Generated by Django 6.0.1 on 2026-02-02 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Daily Progress Report', 'Material Usage Sheet')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('row_headings', models.JSONField(default=list, help_text="List of row heading labels, e.g., ['Task 1', 'Task 2', 'Labor Hours']")),
                ('column_headings', models.JSONField(default=list, help_text="List of column heading labels, e.g., ['Morning', 'Afternoon', 'Evening']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_sheet_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sheet_templates', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_daily_sheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sheet_entries', to='core.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.dailysheettemplate')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySheetCellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='0-based row index')),
                ('column_index', models.PositiveIntegerField(help_text='0-based column index')),
                ('value', models.TextField(blank=True, help_text='Cell value entered by Site Manager')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_data', to='core.dailysheetentry')),
            ],
            options={
                'ordering': ['row_index', 'column_index'],
                'unique_together': {('entry', 'row_index', 'column_index')},
            },
        ),
    ]
